# Generated by Django 4.0.6 on 2022-07-04 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('Reg_no', models.CharField(max_length=70)),
                ('email', models.EmailField(max_length=70)),
                ('Semester', models.IntegerField()),
            ],
        ),
    ]
