# Generated by Django 4.0.6 on 2022-07-04 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='Student',
        ),
    ]
